site: JLC-ART
url: https://seiminomore.github.io/JLC-ART/index.html
title: JLC-ART
description: The JLC-ART Codex is a seamless and intriguing digital archive, presenting the evolving journey of Mr. J.L. Christian's artistic legacy. This curated platform acts as both a museum and a compendium, consolidating his extensive body of work into a cohesive narrative. Each page unveils the layers of esoteric themes, lore, mythos and historical dialogues that define his unique perspective as an artist.
Beyond being a portfolio, the JLC-ART Codex serves as an interactive gateway to the Gumball Arcade Auction House, where high-stakes investment opportunities converge with the world of fine art.
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar: 
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: "/JLC-ART"

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

permalink: /tags/:tag/



collections:

  pages:
    output: true
    permalink: /:name

  posts:
    output: true
    permalink: /:year/:month/:day/:slug

  archives: 
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:

  -  
    scope:
      path: "_post"
      type: "posts"
    values:
      layout: "posts"
      
  - 
    scope:
      path: "archives"
      type: "archives"
    values:
      layout: "archive"
      
  - 
    scope: 
      path: "about"
      type: "about"
    value: 
      layout: "about"

  -
    scope:
      path: "archives"
      type: "archives"
    values:
      layout: "archives"

  -
    scope:
      path: "contacts"
      type: "contacts"
    values:
      layout: "contacts"