site: 
url: https://jlc-art.com
title: JLC-ART
description: The JLC-ART Codex is a digital archive showcasing Mr. J.L. Christian's artistic journey, blending his work with themes of lore, mythos, and history. Acting as both a museum and a portfolio, it offers an interactive gateway to the Gumball Arcade Auction House, connecting fine art with high-stakes investment opportunities.
userpicture: /JLC-card.png

twitter:
  username: jonathanlejon_
  card: The JLC-ART is a digital archive showcasing Mr. J.L. Christian's artistic journey, blending his work with themes of lore, mythos, and history. Acting as both a museum and a portfolio, it offers an interactive gateway to the Gumball Arcade Auction House, connecting fine art with high-stakes investment opportunities.
  creator: jonathanlejon_
author:
  twitter: jonathanlejon_
  name: jonathanlejon_
  avatar: https://seiminomore.github.io/JLC-card.png
  email: emerson.bell@gumballarcade.com
  url: https://x.com/jonathanlejon_

permalink: pretty

baseurl: "/"

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

permalink: /tags/:tag/



collections:

  pages:
    output: true
    permalink: /:name

  posts:
    output: true
    permalink: /:year/:month/:day/:slug

  archives: 
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:

  -  
    scope:
      path: "_post"
      type: "posts"
    values:
      layout: "posts"
      
  - 
    scope:
      path: "archives"
      type: "archives"
    values:
      layout: "archive"
      
  - 
    scope: 
      path: "about"
      type: "about"
    value: 
      layout: "about"

  -
    scope:
      path: "archives"
      type: "archives"
    values:
      layout: "archives"

  -
    scope:
      path: "contacts"
      type: "contacts"
    values:
      layout: "contacts"