site: JLC-ART
url: #yoururl
title: JLC-ART
description: Artworks Codex
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: "/JLC-ART"

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  - 
    scope: 
      path: "about"
      type: "about"
    value: 
      loayout: "about"
  -
    scope:
      path: "contacts"
      type: "contacts"
    values:
      layout: "default"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "_post"
      type: "posts"
    values:
      layout: "post"