site: JLC-ART
url: #yoururl
title: JLC-ART
description: Artworks Codex
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl
permalink: pretty

baseurl: "/JLC-ART"

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

permalink: /tags/:tag/



collections:

  pages:
    output: true
    permalink: /:name

  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:

  -  
    scope:
      path: "_post"
      type: "posts"
    values:
      date: last_modified
      
      
  - 
    scope:
      path: "archives"
      type: "archives"
    values:
      layout: "archive"
      
  - 
    scope: 
      path: "about"
      type: "about"
    value: 
      layout: "about"

  -
    scope:
      path: "archives"
      type: "archives"
    values:
      layout: "archives"

  -
    scope:
      path: "contacts"
      type: "contacts"
    values:
      layout: "contacts"